name: "Add a Permissionless badge"
description: "The user attests to themselves using EAS.attest. The badge contract ensures that the issuer is authorized."
title: "[Badge]: "
labels: ["Permissionless"]
body:
  - type: dropdown
    id: badgeCategory
    attributes:
      label: Badge Category
      options:
        - Status
        - Identity
        - Achievement
      default: 0
    validations:
      required: true
  - type: input
    id: badgeContract
    attributes:
      label: Badge Contract Address
      description: Address of badge contranct deployed on Scroll.
      placeholder: "0xB1Dbd079c62d181926E5A54932Bb1b15F760e8A0"
    validations:
      required: true
  - type: dropdown
    id: eligibilityCheck
    attributes:
      label: Enable isEligible
      description: "Does the badge contract inherit from [ScrollBadgeEligibilityCheck](https://github.com/scroll-tech/canvas-contracts/blob/master/src/badge/examples/ScrollBadgePermissionless.sol)? Note: **No** means everyone is eligible to mint the badge."
      options:
        - "Yes"
        - "No"
      default: 0
    validations:
      required: true
  - type: input
    id: issuerName
    attributes:
      label: Issuer Name
      description: Name of badge issuer. As same as the one listed on [Scroll Ecosystem](https://scroll.io/ecosystem#protocols).
      placeholder: "Scroll"
    validations:
      required: true
  - type: input
    id: issuerURL
    attributes:
      label: Issuer URL
      description: URL of the badge promotional page, If left blank, it defaults to the issuer’s website on [Scroll Ecosystem](https://scroll.io/ecosystem#protocols).
      placeholder: "https://scroll.io"
    validations:
      required: false
  - type: input
    id: communityURL
    attributes:
      label: Community URL
      description: If the user is unable to mint this badge, they can request help through this URL.
      placeholder: "https://discord.gg/B6sU3S7c"
    validations:
      required: true
