name: "Add a Airdropped badge"
description: "Badges can also be issues with no user interaction. To do this, the issuer uses EAS.attest or EAS.multiAttest."
title: "[Badge]: "
labels: ["Airdropped"]
body:
  - type: dropdown
    id: badgeCategory
    attributes:
      label: Badge Category
      options:
        - Status
        - Identity
        - Achievement
      default: 0
    validations:
      required: true
  - type: input
    id: badgeContract
    attributes:
      label: Badge Contract Address
      description: Address of badge contranct deployed on Scroll.
      placeholder: "0xB1Dbd079c62d181926E5A54932Bb1b15F760e8A0"
    validations:
      required: true
  - type: input
    id: baseUrl
    attributes:
      label: BaseURL of Check API
      description: "like {{baseURL}}/check, refer to [Badge APIs](https://scrollzkp.notion.site/Badge-APIs-95890d7ca14944e2a6d34835ceb6b914)"
    validations:
      required: true
  - type: input
    id: issuerName
    attributes:
      label: Issuer Name
      description: Name of badge issuer. As same as the one listed on [Scroll Ecosystem](https://scroll.io/ecosystem#protocols).
      placeholder: "Scroll"
    validations:
      required: true
  - type: input
    id: issuerURL
    attributes:
      label: Issuer URL
      description: URL of the badge promotional page, If left blank, it defaults to the issuer’s website on [Scroll Ecosystem](https://scroll.io/ecosystem#protocols).
      placeholder: "https://scroll.io"
    validations:
      required: false
  - type: input
    id: communityURL
    attributes:
      label: Community URL
      description: If the user is unable to mint this badge, they can request help through this URL.
      placeholder: "https://discord.gg/B6sU3S7c"
    validations:
      required: true
